name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ECR login
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Pull latest image & restart container
        run: |
          docker pull ${{ secrets.ECR_REPO }}:latest
          docker stop sudoku-container || true
          docker rm sudoku-container || true
          docker run -d -p 5080:5000 --name sudoku-container ${{ secrets.ECR_REPO }}:latest
