name: Build & Deploy to EC2 via ECR

on:
  push:
    branches: [ "main" ]   # change if your default branch is different
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      # Secrets:
      ECR_REPO: ${{ secrets.ECR_REPO }}         # full URI: 123456789012.dkr.ecr.us-east-1.amazonaws.com/vehicleproj
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Tag and container config:
      IMAGE_TAG: ${{ github.sha }}
      CONTAINER_NAME: sudoku-app
      CONTAINER_PORT: "8000"    # change if your app listens on a different internal port
      HOST_PORT: "80"           # change host port if 80 is in use

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ✅ ECR login without AWS CLI on the runner
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        run: |
          docker build -t app:${IMAGE_TAG} .
          docker tag app:${IMAGE_TAG} "${ECR_REPO}:${IMAGE_TAG}"
          docker push "${ECR_REPO}:${IMAGE_TAG}"

      - name: Stop old container (if running)
        continue-on-error: true
        run: |
          docker ps -q --filter "name=${CONTAINER_NAME}" | grep -q . && docker stop "${CONTAINER_NAME}" || true
          docker ps -aq --filter "name=${CONTAINER_NAME}" | grep -q . && docker rm "${CONTAINER_NAME}" || true

      - name: Pull and run new container
        run: |
          docker pull "${ECR_REPO}:${IMAGE_TAG}"
          docker run -d --name "${CONTAINER_NAME}" -p ${HOST_PORT}:${CONTAINER_PORT} "${ECR_REPO}:${IMAGE_TAG}"
