# .github/workflows/aws.yaml (relevant parts)

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # 👇 This logs in to ECR without needing aws cli
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push
        env:
          ECR_REPO: ${{ secrets.ECR_REPO }}   # full URI
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t app:${IMAGE_TAG} .
          docker tag app:${IMAGE_TAG} "${ECR_REPO}:${IMAGE_TAG}"
          docker push "${ECR_REPO}:${IMAGE_TAG}"

      # … your stop old container / run new container steps …
