name: Build & Deploy to EC2 via ECR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      # Secrets:
      ECR_REPO: ${{ secrets.ECR_REPO }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Tag and container config:
      IMAGE_TAG: ${{ github.sha }}
      CONTAINER_NAME: sudoku-app
      CONTAINER_PORT: "5000"    # Match Flask's port
      HOST_PORT: "80"           # External port

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        run: |
          docker build -t app:${IMAGE_TAG} .
          docker tag app:${IMAGE_TAG} "${ECR_REPO}:${IMAGE_TAG}"
          docker push "${ECR_REPO}:${IMAGE_TAG}"

      - name: Stop old container (if running)
        continue-on-error: true
        run: |
          docker ps -q --filter "name=${CONTAINER_NAME}" | grep -q . && docker stop "${CONTAINER_NAME}" || true
          docker ps -aq --filter "name=${CONTAINER_NAME}" | grep -q . && docker rm "${CONTAINER_NAME}" || true

      - name: Pull and run new container
        run: |
          docker pull "${ECR_REPO}:${IMAGE_TAG}"
          docker run -d \
            --name "${CONTAINER_NAME}" \
            -p ${HOST_PORT}:5000 \  # Map to container's 5000 port
            -v /app/uploads \      # Persistent storage for uploads
            "${ECR_REPO}:${IMAGE_TAG}"

      - name: Verify deployment
        run: |
          echo "Waiting for container to initialize..."
          sleep 15
          curl --fail http://localhost:${HOST_PORT}/healthz || exit 1
          echo "Health check passed!"